# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: yarn
  - command: npm install near-shell -g --no-optional
    command: brew install tree
    command: clear
